spring:

  # db setting
  datasource:
    url: ENC(nFUPLxrdluVYtSuI+E43seh5G18/RMFxjzJAvKTN+UsnC7bBOu7k1+Nj72VB7EupxNTpKk8XUXI=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(pA+XSpf8G6Sd2EQSfN9gHg==)
    password: ENC(ydBSh/tgI23aXB9zTBLzY0w+vDuAncg8)

  # jpa setting
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: false  # p6spy가 대신 로그를 출력하므로 false로 설정

# query logging setting
logging:
  level:
    root: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari.HikariDataSource: DEBUG
    com.p6spy.engine.spy.P6SpyDriver: DEBUG

# swagger setting
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha # 알파벳 순서로 정렬
    operations-sorter: method # 메소드 순서로 정렬
    doc-expansion: none # 카테고리가 접힌상태로 로딩
    persist-authorization: true # 브라우저를 새로고침 하더라도 인증정보 유지
  packages-to-scan: com.miroit
  title: Initial API 문서 (local)
  version: 1.0

# jwt setting
jwt:
  issuer: initial-api
  access-token-secret-key: initial-api-access-secret_initial-api-access-secret
  access-token-expiration: 2592000000 # 1개월
  refresh-token-secret-key: initial-api-refresh-secret_initial-api-refresh-secret
  refresh-token-expiration: 2592000000 # 1개월

# file
file:
  upload:
    root-path: ENC(vYFR6C8IFEJDglY5D7sC09nw5F2dtvYWnrQguxTiUsw=)
    file-max-size: 10485760 # 10MB (10 * 1024 * 1024)

# 암복호화 빈
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )